In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/supplement_sales.csv")

df.head()

,Order_ID,Order_Date,Customer_ID,Age,Gender,State,Product_Name,Category,Quantity,Unit_Price,Revenue,Payment_Method,Channel,Customer_Type
0,ORD00001,2024-09-27,CUST6191,38,Male,Haryana,Immunity Booster,Immunity,4,649,2596,Debit Card,Flipkart,New
1,ORD00002,2025-10-25,CUST9322,39,Male,Maharashtra,Weight Control Capsules,Weight Management,4,1199,4796,COD,Amazon,New
2,ORD00003,2024-06-09,CUST5555,39,Male,Punjab,Detox Tea,Detox,5,599,2995,UPI,Flipkart,Repeat
3,ORD00004,2025-11-30,CUST1189,20,Male,Karnataka,Hair Serum,Hair Care,4,699,2796,Debit Card,Website,Repeat
4,ORD00005,2025-08-23,CUST9433,26,Female,Bihar,Hair Serum,Hair Care,4,699,2796,Credit Card,Flipkart,Repeat

In [3]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        10000 non-null  str
 1   Order_Date      10000 non-null  datetime64[us]
 2   Customer_ID     10000 non-null  str
 3   Age             10000 non-null  int64
 4   Gender          10000 non-null  str
 5   State           10000 non-null  str
 6   Product_Name    10000 non-null  str
 7   Category        10000 non-null  str
 8   Quantity        10000 non-null  int64
 9   Unit_Price      10000 non-null  int64
 10  Revenue         10000 non-null  int64
 11  Payment_Method  10000 non-null  str
 12  Channel         10000 non-null  str
 13  Customer_Type   10000 non-null  str
dtypes: datetime64[us](1), int64(4), str(9)
memory usage: 1.1 MB

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
invalid_revenue = df[
    df["Revenue"] !=
    df["Quantity"] * df["Unit_Price"]
]

len(invalid_revenue)

0

In [7]:
invalid_age = df[
    (df["Age"] < 18) |
    (df["Age"] > 60)
]

len(invalid_age)

0

In [8]:
df["Year"] = df["Order_Date"].dt.year
df["Month"] = df["Order_Date"].dt.month
df["Month_Name"] = df["Order_Date"].dt.month_name()
df["Quarter"] = df["Order_Date"].dt.quarter

df.head()

,Order_ID,Order_Date,Customer_ID,Age,Gender,State,Product_Name,Category,Quantity,Unit_Price,Revenue,Payment_Method,Channel,Customer_Type,Year,Month,Month_Name,Quarter
0,ORD00001,2024-09-27,CUST6191,38,Male,Haryana,Immunity Booster,Immunity,4,649,2596,Debit Card,Flipkart,New,2024,9,September,3
1,ORD00002,2025-10-25,CUST9322,39,Male,Maharashtra,Weight Control Capsules,Weight Management,4,1199,4796,COD,Amazon,New,2025,10,October,4
2,ORD00003,2024-06-09,CUST5555,39,Male,Punjab,Detox Tea,Detox,5,599,2995,UPI,Flipkart,Repeat,2024,6,June,2
3,ORD00004,2025-11-30,CUST1189,20,Male,Karnataka,Hair Serum,Hair Care,4,699,2796,Debit Card,Website,Repeat,2025,11,November,4
4,ORD00005,2025-08-23,CUST9433,26,Female,Bihar,Hair Serum,Hair Care,4,699,2796,Credit Card,Flipkart,Repeat,2025,8,August,3

In [9]:
df.to_csv(
    "../data/processed/clean_supplement_sales.csv",
    index=False
)

print("Clean dataset saved successfully.")

Clean dataset saved successfully.